### ISSUE TITLE
As a site visitor, I would like to see reviews of the lessons and the teacher so that I can make an informed decision whether this is the right teacher for me. 

### ISSUE THREAD

**Issue by GiuliaAndriuolo** [Cathy-s-Piano-Studio-Wordpress/website#2]
**Description**
Social proof to highlight her expertise and teaching methods.
Experiences are currently mainly shared in personal conversations with students, however sharing them on the homepage can assist her with reaching more people and even prospective students

**Definition of Done (DoD)**
Two team members select and add the the quotes from Cathy's current clients
- short reviews or quotes are added
- The statement is approved by all the team memebers and by Cathy

**Subtasks**
- [x] Add quotes from satisfied students/clients to send a direct message of the main strengths of Cathy's lessons at the bottom of the homepage
- [x] Before the quote insert an opening catchy statement

**Comment by sofiacommandeur** [comment]
Sofia added quotes of current students to the landing page as reviews
<img width="1112" alt="Schermafbeelding 2021-03-17 om 14 15 33" src="https://user-images.githubusercontent.com/80045934/111473812-b716cb80-872b-11eb-85b0-8089dec1f01a.png">
