### ISSUE TITLE
As an artist, I need to share my thoughts and opinions on the music world with everybody in order to inspire others. 

### ISSUE THREAD

**Issue by GiuliaAndriuolo** [Cathy-s-Piano-Studio-Wordpress/website#4]
Description:
Cathy is currently using Wordpress and her blog to share her professional opinions about the music world.

Definition of Done (DoD):

- The whole team select soundtrack to upload. Two team members create a short list of sound tracks in the format of a typical itunes list. Each audio last no more around 2-3 minutes. The rest of the group test the functionality
- A team member asks Cathy for promotional material from her past events
- A team member asks Cathy for her reflections and philosophy of work and two team member summarize and upload the contents
- The new blog section is created by two team members and approved by the whole team

Subtasks:

- [x] Addition of short list of 2 or 3, max 5 audio played by Cathy. It could be part of a "Media" section
- [x] Information about past events + call to action to sign up and become part of the students group
- [x] Add brief reflections from Cathy on music teaching and piano music
- [x] Create a blog section with a button and link to her personal blog

**Comment by sophiekossmann1611** [comment]
Tuesday 09/03/21
Created subpage with multiple sections:

Section 1 :1 column
- call-to-action button: Book free lesson on the top right of the page 
- Title: Gallery & Events
- Textfield (two or three short sentences to start the page)

Section 2: 
- Title: Past events
- Text field: to add something about events in general 
Subsection with 3 columns: 
- left column: picture from event x, below a text field with name of the event (for now Event X) and short description
- middle column: picture from event y, below a text field with name of the event (for now Event Y) and short description
- right column: picture from event z, below a text field with name of the event (for now Event Z) and short description

Section 3: 
- Title: Videos 
- picture of someone playing piano + Text Field (1-2 sentences about videos) 
Subsection: 2 columns
- left column: video added
- right column: video added

Section 4: 1 column

- Title: Want to learn more about me or get in contact? 
Subsection: 2 columns
- left columns: Textfield (Check out social media) + Social media Buttons and Links 
- right column: Textfield (Contact me)
- Call-to-action button: Book free lesson 

![image](https://user-images.githubusercontent.com/79995095/110662326-b0d19e00-81c5-11eb-8e9f-86d364442456.png)

![image](https://user-images.githubusercontent.com/79995095/110662397-c1821400-81c5-11eb-8f8a-bf24e22d18ec.png)

![image](https://user-images.githubusercontent.com/79995095/110662449-ce9f0300-81c5-11eb-97dd-7398a099abbc.png)

![image](https://user-images.githubusercontent.com/79995095/110662544-e5ddf080-81c5-11eb-8046-b2378294ac4d.png)

**Comment by sophiekossmann1611** [comment]
Giulia and Sophie are responsible for the technical set up of this subpage
Amina and Sofia are responsible for the text of this subpage

**Comment by GiuliaAndriuolo** [comment]
Thursday 11-03-21 update:
Cathy has already a blog in place on a separate platform from WordPress.

Giulia suggested to link her existing blog to one of the subpages in our website, instead of creating a new blog section on the website so that:

-Cathy can easily continue to work on her blog without having to make changes to the website structure. 
-The general visitor is not overwhelmed by too much information out of the website scope
-We keep the focus on the marketing goal of attracting new clients.
-If interested in learning more about Cathy's philosophy and thoughts, the general visitor can be redirected to her blog for more 

Amina suggests that we insert a link to the blog in the Events section.

**Comment by sofiacommandeur** [comment]
- Sofia added video's and descriptions of past events to the "Events" Subpage

<img width="1119" alt="Schermafbeelding 2021-03-17 om 15 06 56" src="https://user-images.githubusercontent.com/80045934/111481042-de24cb80-8732-11eb-9989-7b08038f0632.png">
<img width="1113" alt="Schermafbeelding 2021-03-17 om 15 07 06" src="https://user-images.githubusercontent.com/80045934/111481025-da914480-8732-11eb-94f4-2c54d014817e.png">

**Comment by sophiekossmann1611** [comment]
**Sunday - 21/03** 

Added section to page with link to her blog 

![image](https://user-images.githubusercontent.com/79995095/111915813-60392b00-8a78-11eb-9c07-8b1663ce1e55.png)

**Comment by AminaElJaadi** [comment]
Blog and social media are used to create the text for the events page. We discussed with Cathy the events that are the most important and that she wants to highlight on this page. 

Before describing the events a short quote is added: "More than piano lessons, a unique experience!"  with the heading My Events. 

![image](https://user-images.githubusercontent.com/80032113/111923789-24ff2200-8aa1-11eb-81ba-803051e8c480.png)

The first version of the page with the text and the second version that is updated after receiving more content from Cathy.

![image](https://user-images.githubusercontent.com/80032113/111923822-54159380-8aa1-11eb-9c4f-cc3d6dcb3f8e.png)

![image](https://user-images.githubusercontent.com/80032113/111923831-6263af80-8aa1-11eb-911a-6cf20caab9f4.png)
